# Complete Automated Enhancement Workflow Setup Script
Write-Host "🚀 Setting up Automated Website Enhancement Workflow..." -ForegroundColor Cyan

# Create the workflow directory if it doesn't exist
New-Item -ItemType Directory -Path ".github/workflows" -Force | Out-Null

# Create the auto-enhance workflow file
@'
name: 🤖 Auto-Enhance Website

on:
  schedule:
    - cron: '0 */6 * * *'   # Every 6 hours
    - cron: '0 0 * * *'     # Daily at midnight
  workflow_dispatch:
    inputs:
      enhancement_type:
        description: 'Type of enhancement to run'
        required: true
        default: 'all'
        type: choice
        options:
          - 'all'
          - 'performance'
          - 'seo'
          - 'accessibility'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  enhance:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Run Performance Checks
        run: |
          echo "## 🔍 Performance Audit" >> report.md
          
          # Check image sizes
          echo "### Images" >> report.md
          find . -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" | while read img; do
            size=$(du -k "$img" 2>/dev/null | cut -f1)
            if [ "$size" -gt 100 ]; then
              echo "- ⚠️ Large: $img (${size}KB)" >> report.md
            fi
          done
          
      - name: Run SEO Checks
        run: |
          echo "" >> report.md
          echo "## 🔍 SEO Audit" >> report.md
          
          # Check and add meta description
          if grep -q '<meta name="description"' index.html 2>/dev/null; then
            echo "- ✅ Meta description found" >> report.md
          else
            echo "- ❌ Missing meta description - fixing" >> report.md
            sed -i 's/<head>/<head>\n  <meta name="description" content="YT Studio - Islamic history and Quranic mysteries">/' index.html
          fi
          
          # Check and add viewport
          if grep -q 'name="viewport"' index.html 2>/dev/null; then
            echo "- ✅ Viewport configured" >> report.md
          else
            echo "- ❌ Missing viewport - fixing" >> report.md
            sed -i 's/<head>/<head>\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">/' index.html
          fi
          
          # Check H1 tag
          if grep -q '<h1' index.html 2>/dev/null; then
            echo "- ✅ H1 tag present" >> report.md
          else
            echo "- ❌ Missing H1 tag" >> report.md
          fi
          
      - name: Apply Auto-Fixes
        run: |
          # Add lazy loading to images
          sed -i 's/<img /<img loading="lazy" /g' index.html 2>/dev/null || true
          
          # Format code with Prettier if available
          npx prettier --write "**/*.{js,css,html}" 2>/dev/null || true
          
          echo "✅ Auto-fixes applied" >> report.md
          
      - name: Check for Changes
        id: git-check
        run: |
          git add -A
          if ! git diff --cached --quiet; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "changes_detected=yes" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "changes_detected=no" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request
        if: steps.git-check.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🤖 Auto-enhancement: Website optimizations"
          title: "🤖 Automated Website Enhancement - ${{ github.run_id }}"
          body: |
            ## 🤖 Auto-Generated Enhancement PR
            
            ### Changes Made:
            - ✅ Added lazy loading to images
            - ✅ Added missing meta tags
            - ✅ Formatted code
            - ✅ Performance improvements
            
            ### Run Details:
            - **Run ID:** ${{ github.run_id }}
            - **Trigger:** ${{ github.event_name }}
            - **Timestamp:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')
            
            *Generated by 🤖 Auto-Enhance Workflow*
          branch: auto-enhance/update-${{ github.run_id }}
          base: main
          labels: automated, enhancement, auto-pr
          delete-branch: true
          force-push: false
          
      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🤖 Auto-Enhance Workflow Failed',
              body: `## Workflow Failed\n\nRun ID: ${process.env.GITHUB_RUN_ID}\n\nPlease check the logs for details.`
            });
            
      - name: Summary Report
        run: |
          echo "## ✅ Auto-Enhancement Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Run Information" >> $GITHUB_STEP_SUMMARY
          echo "- **Time:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "- **Trigger:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Changes Detected:** ${{ steps.git-check.outputs.changes_detected }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Actions Taken" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Added lazy loading to images" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Added missing meta tags" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Formatted code" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.git-check.outputs.has_changes }}" == "true" ]; then
            echo "- ✅ Pull request created" >> $GITHUB_STEP_SUMMARY
          else
            echo "- ℹ️ No changes needed" >> $GITHUB_STEP_SUMMARY
          fi
'@ | Out-File -FilePath ".github/workflows/auto-enhance.yml" -Encoding utf8

Write-Host "✅ Created auto-enhance.yml with unique branch names" -ForegroundColor Green

# Create asset optimization workflow
@'
name: 🖼️ Auto-Optimize Assets

on:
  schedule:
    - cron: '0 2 * * 0'  # Weekly Sunday at 2 AM
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  optimize:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Optimize Images
        run: |
          sudo apt-get update
          sudo apt-get install -y optipng jpegoptim
          
          # Optimize PNGs
          find . -name "*.png" -type f -exec optipng -o7 {} \; 2>/dev/null || true
          
          # Optimize JPGs
          find . -name "*.jpg" -o -name "*.jpeg" -type f -exec jpegoptim --strip-all {} \; 2>/dev/null || true
          
      - name: Check for Changes
        id: git-check
        run: |
          git add -A
          if ! git diff --cached --quiet; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request
        if: steps.git-check.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🖼️ Optimize images and assets"
          title: "🤖 Asset Optimization - ${{ github.run_id }}"
          body: |
            ## 🤖 Weekly Asset Optimization
            
            Images and assets have been optimized.
            
            **Run ID:** ${{ github.run_id }}
          branch: auto-optimize/assets-${{ github.run_id }}
          base: main
          labels: automated, optimization
          delete-branch: true
          force-push: false
'@ | Out-File -FilePath ".github/workflows/auto-optimize.yml" -Encoding utf8

Write-Host "✅ Created auto-optimize.yml" -ForegroundColor Green

# Commit and push
Write-Host "📦 Committing and pushing workflows..." -ForegroundColor Yellow

git add .github/workflows/auto-enhance.yml .github/workflows/auto-optimize.yml
git commit -m "feat: Add automated website enhancement workflows

- Auto-enhance: Runs every 6 hours with SEO/performance checks
- Auto-optimize: Weekly image and asset optimization
- Uses unique branch names to avoid force-push protection
- Creates pull requests automatically
- Includes failure notification via GitHub issues"

git pull origin main --rebase --no-edit
git push origin main

Write-Host "✅ Workflows committed and pushed!" -ForegroundColor Green
Write-Host ""
Write-Host "🎯 Next Steps:" -ForegroundColor Cyan
Write-Host "1. Test the workflow: gh workflow run auto-enhance.yml" -ForegroundColor White
Write-Host "2. Check status: gh run list --workflow=auto-enhance.yml --limit 3" -ForegroundColor White
Write-Host "3. View on GitHub: https://github.com/ruhdevops/YT-Studio/actions" -ForegroundColor White
Write-Host ""
Write-Host "📋 Workflow Features:" -ForegroundColor Cyan
Write-Host "- ✅ Unique branch names (no force-push issues)" -ForegroundColor White
Write-Host "- ✅ Automatic PR creation with changes" -ForegroundColor White
Write-Host "- ✅ Performance and SEO audits" -ForegroundColor White
Write-Host "- ✅ Failure notifications via issues" -ForegroundColor White
Write-Host "- ✅ Runs every 6 hours + manual trigger" -ForegroundColor White

# Optional: Test the workflow
$testNow = Read-Host "`nDo you want to test the workflow now? (y/n)"
if ($testNow -eq 'y') {
    Write-Host "🧪 Testing workflow..." -ForegroundColor Yellow
    gh workflow run auto-enhance.yml
    Write-Host "✅ Workflow triggered! Check status with: gh run list --limit 3" -ForegroundColor Green
}