python-checks:
  docker:
    - image: cimg/python:3.12
  steps:
    - checkout
    - run:
        name: Install UV
        command: curl -LsSf https://astral.sh/uv/install.sh | sh
    - run:
        name: Install dependencies
        command: uv pip install -r requirements-dev.txt
    - run:
        name: Run Ruff
        command: ruff check . --fix && ruff format .
    - run:
        name: Run MyPy
        command: mypy .
    - run:
        name: Run tests
        command: pytest
